# Generated by Django 5.0.2 on 2025-03-14 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_alter_concert_available_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=100)),
                ('purchased_on', models.DateTimeField(auto_now_add=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.concert')),
            ],
        ),
    ]
